---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: wheezy-64
  driver_config:
    box: wheezy64
    box_url: http://debbuild.bigpoint.net/wheezy64.box
    network:
    - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 8080, host: 8081, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 4443, auto_correct: true}]
    - ["private_network", {ip: "8.1.1.8"}]
    customize:
      memory: 1024

suites:
  - name: icinga
    data_bags_path: "test/integration/default/data_bags"
    #encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[icinga::server]
      - recipe[exim4-light]
    attributes:
      set_fqdn: "icinga-server-01.local"
      check_mk: 
        groups: 
          - "check-mk-admin"
          - "check-mk-guest"
        isMaster: "False"
        config: 
          ignored_services: 
            - "ALL_HOSTS, [ \"Monitoring\" ]"
          ignored_checks: 
            - "[ \"mysql_capacity\" ], ALL_HOSTS"
        notifications: 
          email: 
            disabled: "True"
          sms: 
            disabled: "True"
        exim4: 
          configtype: "internet"
        pnp4nagios: 
          htpasswd: 
            file: "/etc/icinga/htpasswd.users"
        rrdcached: 
          config: 
            options: "-s nagios -m 0660 -l unix:/var/run/rrdcached/rrdcached.sock -F -w 1800 -z 1800"
            socket: "unix:/var/run/rrdcached rrdcached.sock"

